#!/usr/bin/env python3
"""Install Bosun's Claude agents at project scope with an explicit verifier effort."""

import argparse
from pathlib import Path
import re
import sys

MODES = ("fable", "fable-crew", "fable-opus", "opus")
OPUS_MODEL = "claude-opus-5-5"
FABLE_MODEL = "claude-fable-5-1"

EFFORTS = ("low", "medium", "high", "xhigh", "max")
MARKER = "<!-- Generated by Bosun configure-claude-agents.py; edit the shipped templates instead. -->"


def configure(args):
    project = Path(args.project).resolve(strict=True)
    if not project.is_dir():
        raise ValueError("--project must be a directory")
    directory = project / ".claude" / "agents"
    for path in (project / ".claude", directory):
        if path.is_symlink() or (path.exists() and not path.is_dir()):
            raise ValueError(f"refusing non-directory or symlink: {path}")
    model = OPUS_MODEL if args.mode == "opus" else FABLE_MODEL
    names = ["bosun-scout", "bosun-verifier", "bosun-verifier-mobile"]
    if args.include_worker or args.mode == "fable-opus":
        names.append("bosun-worker-opus")
    templates = Path(__file__).resolve().parent.parent / "agents"
    pending = []
    for name in names:
        source = (templates / f"{name}.md").read_text()
        parts = source.split("---", 2)
        if len(parts) != 3 or parts[0]:
            raise ValueError(f"invalid agent frontmatter: {name}")
        if name != "bosun-worker-opus":
            parts[1], count = re.subn(r"^model: .+$", f"model: {model}", parts[1], flags=re.M)
            if count == 0:
                parts[1] += f"model: {model}\n"
            elif count != 1:
                raise ValueError(f"expected at most one model field: {name}")
        if name.startswith("bosun-verifier"):
            parts[1], count = re.subn(r"^effort: .+$", f"effort: {args.verifier_effort}", parts[1], flags=re.M)
            if count != 1:
                raise ValueError(f"expected exactly one effort field: {name}")
        content = "---".join(parts) + "\n" + MARKER + "\n"
        target = directory / f"{name}.md"
        if target.is_symlink():
            raise ValueError(f"refusing symlink: {target}")
        if target.exists() and (not target.is_file() or MARKER not in target.read_text()):
            raise ValueError(f"refusing to overwrite a user-owned agent: {target}")
        pending.append((target, content))
    # Validate every destination and template before changing anything.
    if not args.dry_run:
        directory.mkdir(parents=True, exist_ok=True)
    for target, content in pending:
        if not args.dry_run and (not target.exists() or target.read_text() != content):
            target.write_text(content)
        print(f"{'Would configure' if args.dry_run else 'Configured'} {target}")
    print(f"Verifier: {model} / {args.verifier_effort}")
    print(f"Scout: {model} / medium")
    if args.include_worker or args.mode == "fable-opus":
        print(f"Worker: {OPUS_MODEL} / high")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", required=True, help="Project root (contains the spec)")
    parser.add_argument("--mode", choices=MODES, default="fable", help="Claude provider mode; selects scout and verifier models")
    parser.add_argument("--verifier-effort", choices=EFFORTS, default="high")
    parser.add_argument("--include-worker", action="store_true", help="Also install the Opus worker (legacy; fable-opus includes it automatically)")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print targets without writing")
    args = parser.parse_args()
    if args.include_worker and args.mode == "opus":
        parser.error("--include-worker is not used in opus mode; the lead implements directly")
    try:
        configure(args)
    except (OSError, ValueError) as error:
        print(f"configure-claude-agents: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
